params:
  test: testkeyword
  epochs: 30
  batchsize: 32
  no_classes: 10
  loss_function: stoch_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000


artifacts:
  artifacts_dir: artifacts
  model_dir: model
  plots.dir: plots
  checkpoint_dir: checkpoints

logs:
  logs_dir: logs_dir
  general_logs: general_logs
  tensorflow_logs: tensorflow_logs